apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-config
data:
  RAILS_ENV: development
  RAILS_SERVE_STATIC_FILES: "true"
  DB_HOSTNAME: $RDS_ENDPOINT
  DB_USERNAME: mysql_user
  DB_PASSWORD: mysql_user
  DATABASE_NAME: weatherreportdb
