version: '3.7'

x-web-container: &web-container
  environment:
    DB_USERNAME: mysql_user
    DB_PASSWORD: mysql_user
    DB_HOSTNAME: db_latest    
    RAILS_SERVE_STATIC_FILES: 'true'
    OPENWEATHERMAP_API_KEY:
    DATABASE_NAME: weatherreportdb

services:
  db_latest:
    build:
      context: ./database
      args:
        env_database: development
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"

  server_latest:
    << : *web-container
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    ports:
      - '3000:3000'
    depends_on:
      - db_latest

  client_latest:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - HOST_NAME=server_latest
    ports:
      - '8080:80'
    depends_on:
      - server_latest
