version: '3.7'

x-web-container: &test-web-container
  environment:
    TZ: 'Asia/Tokyo'
    MYSQL_PASS_DEVELOPMENT: mysql_user
    MYSQL_USER_DEVELOPMENT: mysql_user
    RAILS_SERVE_STATIC_FILES: 'true'
    DB_SERVICE_NAME: 'db'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: weather_report_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_user
    volumes:
      - ./data/db_test:/var/lib/mysql
    ports:
      - "3306:3306"

  # db migration after mysql startup
  db-migrate:
    << : *test-web-container
    build: .
    depends_on:
      - db
    command: './wait-for-it.sh -t 60 -h db -p 3306 -- bin/rails db:migrate RAILS_ENV=test'

  web:
    << : *test-web-container
    build: .
    command: sh -c "rm -rf tmp && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - ./app/controllers:/weather_report/app/controllers
      - ./app/models:/weather_report/app/models
      - ./app/views:/weather_report/app/views      
      - ./spec:/weather_report/spec
    depends_on:
      - db-migrate
