version: '3.7'

x-web-container: &web-container
  build: .
  environment:
    TZ: 'Asia/Tokyo'
    MYSQL_PASS_DEVELOPMENT: mysql_user
    MYSQL_USER_DEVELOPMENT: mysql_user
    RAILS_SERVE_STATIC_FILES: 'true'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: weather_report_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_user
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"

  # db migration after mysql startup
  db-migrate:
    << : *web-container
    depends_on:
      - db
    command: './wait-for-it.sh -t 60 -h db -p 3306 -- bin/rails db:migrate RAILS_ENV=development'

  web:
    << : *web-container
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db-migrate
