version: '3.7'

x-web-container: &web-container
  environment:
    MYSQL_PASS: mysql_user
    MYSQL_USER: mysql_user
    RAILS_SERVE_STATIC_FILES: 'true'
    DB_SERVICE_NAME: 'db'
    OPENWEATHERMAP_API_KEY:
    MYSQL_DATABASE: weather_report_production

services:
  db_latest:
    build:
      context: .
      args:
        env_database: production
      dockerfile: Dockerfile.db
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"

  # db migration after mysql startup
  db-migrate:
    << : *web-container
    build: 
      context: .
      args:
        rails_env: production
      dockerfile: Dockerfile.migration
    depends_on:
      - db_latest
    ports:
      - "3307:3307"

  db-openweathermap:
    << : *web-container
    build:
      context: .
      dockerfile: Dockerfile.openWeatherMap
    depends_on: 
      - db-migrate
    command: sh -c "./wait-for-it.sh -t 60 -h db_latest -p 3306 && ruby current_weather_insert.rb"

  server_latest:
    << : *web-container
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '3000:3000'
    depends_on:
      - db-migrate

  client_latest:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '8080:8080'
    depends_on:
      - server_latest
