apiVersion: apps/v1
kind: Deployment
metadata:
  name:  weatherreport-development
  labels:
    app: weatherreport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherreport
  template:
    metadata:
      labels:
        app: weatherreport
    spec:
      containers:
      - name: vue
        image: weatherreport_client_latest
        #imagePullPolicy: Always
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: vue-config
      - name: rails
        image: weatherreport_server_latest
        #imagePullPolicy: Always
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: rails-config

---
kind: Service
apiVersion: v1
metadata:
  name:  weatherreport-service
spec:
  type:  LoadBalancer
  selector:
    app: weatherreport
  ports:
  - protocol: TCP
    port:  8080
    targetPort:  80