version: "3.7"

services:
  deploy:
    build: .
    environment:
      - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - KUBECONFIG=/workdir/.kube/config
      - RDS_ENDPOINT=$RDS_ENDPOINT
      - AWS_ECR_REPOSITORY_NAME=$AWS_ECR_REPOSITORY_NAME
      - FRONTEND_IMAGE_NAME=$FRONTEND_IMAGE_NAME
      - FRONTEND_IMAGE_VERSION=$FRONTEND_IMAGE_VERSION
      - BACKEND_IMAGE_NAME=$BACKEND_IMAGE_NAME
      - BACKEND_IMAGE_VERSION=$BACKEND_IMAGE_VERSION
    privileged: true
    tty: true
