apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app:  mysql
  type:  ClusterIP
  clusterIP: None
  ports:
    - port:  3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_USER
          value: mysql_user
        - name: MYSQL_PASSWORD
          value: mysql_user
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc

        
