name: Static Analysis

on: push

jobs:
  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install bundle
        run:
          gem install bundler:2.0.1
          bundle install
        working-directory: ./backend