version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
        environment:
          BUNDLE_JOBS: '3'
          BUNDLE_RETRY: '3'
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
    # ディレクトリ情報を移動（こうしないとエラーになる）
    working_directory: ~/WeatherReport
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: gem install bundler:2.0.1
      - run: bundle check
      - run: bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # run tests!
      - run:
          name: run tests
          command: 
            # ruby test/models/weather/all_test.rb
            bundle exec rspec spec/models/weather/*

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
