version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@1.0.4

aliases:
  - &default_env
    environment:
      SUDO_COMMAND: ""
  - &change_command
    run:
      name: change sudo command
      command: |
        if [[ $CIRCLE_SHELL_ENV =~ "localbuild" ]]; then
          echo 'export SUDO_COMMAND=sudo' >> $BASH_ENV
        fi

executors:
  default:
    working_directory: ~/WeatherReport
    docker:
      - image: circleci/ruby:2.6.5

commands:
  restore_server_pkg:
    steps:
      - restore_cache:
          name: Restore server container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "Dockerfile.server" }}

  restore_db_migrate_pkg:
    steps:
      - restore_cache:
          name: Restore db-migrate container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "Dockerfile.migration" }}
  restore_client_pkg:
    steps:
      - restore_cache:
          name: Restore client container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "Dockerfile.frontend" }}

  save_server_pkg:
    steps:
      - save_cache:
          name: Save server container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "Dockerfile.server" }}
          paths:
            - ~/WeatherReport/

  save_db_migrate_pkg:
    steps:
      - save_cache:
          name: Save db-migrate container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "Dockerfile.migration" }}
          paths:
            - ~/WeatherReport/
  
  save_client_pkg:
    steps:
      - save_cache:
          name: Save client container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "Dockerfile.frontend" }}
          paths:
            - ~/WeatherReport/frontend/

  test_container:
    steps:
      - *change_command
      - run:
          name: docker-compose up
          command: |
            set -x
            ${SUDO_COMMAND} docker-compose -f docker-compose.test.yml up -d

      - run:
          name: sleep for waiting launch db
          command: |
            sleep 30

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
            ${SUDO_COMMAND} docker-compose -f docker-compose.test.yml exec server_latest bundle exec rspec --format progress \
                                                                  --format RspecJunitFormatter \
                                                                  --out /tmp/test-results/rspec.xml \
                                                                  $TEST_FILES

      # Save test results for timing analysis
      - store_test_results:
          path: /tmp/test-results

      - run:
          name: docker-compose down
          command: |
            set -x
            ${SUDO_COMMAND} docker-compose -f docker-compose.test.yml down

jobs:
  setup:
    executor: default
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: WeatherReport
      - aws-cli/install
      - aws-cli/configure:
          profile-name: my-profile-name
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION

  test:
    executor: default
    steps:
      - checkout
      - *change_command      
      - setup_remote_docker
      - restore_server_pkg
      - restore_db_migrate_pkg
      - restore_client_pkg
      - test_container
      - save_server_pkg
      - save_db_migrate_pkg
      - save_client_pkg

  deploy:
    executor: default
    steps:
      - checkout
      - restore_server_pkg
      - restore_db_migrate_pkg
      - restore_client_pkg      
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
         account-url: AWS_ECR_ACCOUNT_URL
         dockerfile: Dockerfile.db
         region: AWS_REGION
         repo: $AWS_ECR_REPOSITORY
         extra-build-args: '--build-arg env_database=production'
         tag: 'db_latest'
      - aws-ecr/build-and-push-image:
         account-url: AWS_ECR_ACCOUNT_URL
         dockerfile: Dockerfile.migration
         region: AWS_REGION
         repo: $AWS_ECR_REPOSITORY
         extra-build-args: '--build-arg rails_env=production'
         tag: 'db-migrate_latest'
      - aws-ecr/build-and-push-image:
         account-url: AWS_ECR_ACCOUNT_URL
         dockerfile: Dockerfile.server
         region: AWS_REGION
         repo: $AWS_ECR_REPOSITORY
         tag: 'server_latest'
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile.frontend
          region: AWS_REGION
          repo: $AWS_ECR_REPOSITORY
          tag: 'client_latest'         
workflows:
  setup_and_build:
    jobs:
      - setup
      #- test:
      #    requires:
      #      - setup
      - deploy:
          #requires:
          #  - test
          filters:
            branches:
              only: release
      - aws-ecs/deploy-service-update:
          requires:
            - deploy
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=db_latest,tag=db_latest'
          filters:
            branches:
              only: release  
      - aws-ecs/deploy-service-update:
          requires:
            - deploy
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=db-migrate_latest,tag=db-migrate_latest'
          filters:
            branches:
              only: release
      - aws-ecs/deploy-service-update:
          requires:
            - deploy
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=server_latest,tag=server_latest'
          filters:
            branches:
              only: release
      - aws-ecs/deploy-service-update:
          requires:
            - deploy
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=client_latest,tag=client_latest'
          #filters:
            #branches:
              #only: release         
