version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@1.0.4

aliases:
  - &default_env
    environment:
      SUDO_COMMAND: ""
  - &change_command
    run:
      name: change sudo command
      command: |
        if [[ $CIRCLE_SHELL_ENV =~ "localbuild" ]]; then
          echo 'export SUDO_COMMAND=sudo' >> $BASH_ENV
        fi

executors:
  default:
    working_directory: ~/WeatherReport
    docker:
      - image: circleci/ruby:2.6.5
  terraform_machine:
    working_directory: ~/WeatherReport
    docker:
      - image: hashicorp/terraform:0.12.23

commands:
  restore_server_pkg:
    steps:
      - restore_cache:
          name: Restore server container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "backend/Dockerfile.server" }}

  restore_db_migrate_pkg:
    steps:
      - restore_cache:
          name: Restore db-migrate container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "backend/Dockerfile.migration" }}
  restore_client_pkg:
    steps:
      - restore_cache:
          name: Restore client container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "frontend/Dockerfile.frontend" }}

  save_server_pkg:
    steps:
      - save_cache:
          name: Save server container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "backend/Dockerfile.server" }}
          paths:
            - ~/WeatherReport/backend

  save_db_migrate_pkg:
    steps:
      - save_cache:
          name: Save db-migrate container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "backend/Dockerfile.migration" }}
          paths:
            - ~/WeatherReport/backend

  save_client_pkg:
    steps:
      - save_cache:
          name: Save client container
          key: docker-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "frontend/Dockerfile.frontend" }}
          paths:
            - ~/WeatherReport/frontend/

  bundle_install:
    steps:
      - run:
          name: bundle install
          command: |
            cd ~/WeatherReport/backend
            bundle install
            cd ~/WeatherReport

  rubocop_container:
    steps:
      - *change_command
      - run:
          name: run rubocop
          command: |
            cd ~/WeatherReport/backend
            ${SUDO_COMMAND} bundle exec rubocop
            cd ~/WeatherReport


  test_container:
    steps:
      - *change_command
      - run:
          name: run unit tests
          command: |
            ${SUDO_COMMAND} docker-compose -f docker-compose.test.yml run --rm db-openweathermap sh -c 'cd .. && bundle install && env &&rake test -f spec/rakefile'
      
      - run:
          name: migrate db
          command: |
            ${SUDO_COMMAND} docker-compose -f docker-compose.test.yml run --rm db-migrate bundle exec rake db:migrate

      - run:
          name: run rspec
          command: |
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
            ${SUDO_COMMAND} docker-compose -f docker-compose.test.yml run --rm server_latest bundle exec rspec --format progress \
                                                                  --format RspecJunitFormatter \
                                                                  --out /tmp/test-results/rspec.xml \
                                                                  $TEST_FILES

      # Save test results for timing analysis
      - store_test_results:
          path: /tmp/test-results

      - run:
          name: docker-compose down
          command: |
            set -x
            ${SUDO_COMMAND} docker-compose -f docker-compose.test.yml down


  apply_manifest:
    steps:
      - run:
          name: Apply manifest
          command: |
            cd deploy/k8s
            ${SUDO_COMMAND} docker-compose -f docker-compose.yml build --force-rm
            ${SUDO_COMMAND} docker-compose -f docker-compose.yml run --rm deploy sh -c 'sh apply.sh'

jobs:
  setup:
    executor: default
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: WeatherReport
      #- aws-cli/install
      #- aws-cli/configure:
      #    profile-name: my-profile-name
      #    aws-access-key-id: AWS_ACCESS_KEY_ID
      #    aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      #    aws-region: AWS_REGION

  test:
    executor: default
    steps:
      - checkout
      - *change_command      
      - setup_remote_docker
      - restore_server_pkg
      - restore_db_migrate_pkg
      - restore_client_pkg
      - test_container
      - save_server_pkg
      - save_db_migrate_pkg
      - save_client_pkg

  plan_terraform:
    executor: terraform_machine
    environment:
      S3_BUCKET: yamashii-terraform
      AWS_REGION: ap-northeast-1
      TERRAFROM_VER: 0.12.23
    steps:
      - checkout
      - run:
          name: Change directory
          command: cd deploy/terraform
      - run:
          name: Init terraform
          command: terraform init
      - run:
          name: Plan terraform
          command: terraform plan
    
  apply_terraform:
    executor: terraform_machine
    environment:
      S3_BUCKET: yamashii-terraform
      AWS_REGION: ap-northeast-1
      TERRAFROM_VER: 0.12.23
    steps:
      - checkout
      - run:
          name: Change directory
          command: cd deploy/terraform
      - run:
          name: Init terraform
          command: terraform init
      - run:
          name: Apply terraform
          command: terraform apply -auto-approve

  destroy_terraform:
    machine: true
    environment:
      S3_BUCKET: yamashii-terraform
      AWS_REGION: ap-northeast-1
      TERRAFROM_VER: 0.12.23
    steps:
      - checkout
      - run:
          name: Change directory
          command: cd deploy/terraform
      - run:
          name: Init terraform
          command: terraform init
      - run:
          name: Destroy terraform
          command: terraform destroy -auto-approve

  push_images:
    executor: default
    steps:
      - checkout
      - restore_server_pkg
      - restore_db_migrate_pkg
      - restore_client_pkg      
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
         account-url: AWS_ECR_ACCOUNT_URL
         dockerfile: Dockerfile.db
         region: AWS_REGION
         repo: $AWS_ECR_REPOSITORY
         extra-build-args: '--build-arg env_database=development'
         tag: 'db_latest'
      - aws-ecr/build-and-push-image:
         account-url: AWS_ECR_ACCOUNT_URL
         dockerfile: Dockerfile.migration
         region: AWS_REGION
         repo: $AWS_ECR_REPOSITORY
         extra-build-args: '--build-arg rails_env=development'
         tag: 'db-migrate_latest'
      - aws-ecr/build-and-push-image:
         account-url: AWS_ECR_ACCOUNT_URL
         dockerfile: Dockerfile.server
         region: AWS_REGION
         repo: $AWS_ECR_REPOSITORY
         extra-build-args: '--build-arg rails_env=development'
         tag: 'server_latest'
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile.frontend
          region: AWS_REGION
          repo: $AWS_ECR_REPOSITORY
          tag: 'client_latest' 

  apply_manifest:
    executor: default
    steps:
      - checkout
      - *change_command
      - setup_remote_docker
      - apply_manifest

workflows:
  test_and_deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - plan_terraform:
          requires:
            - test
      - apply_terraform:
          requires:
            - plan_terraform
          filters:
            branches:
              only:
                - feature-215
      - destroy_terraform:
          requires:
            - apply_terraform
          filters:
            branches:
              only:
                - feature-215
      - push_images:
          requires:
            - apply_terraform
          filters:
            branches:
              only: 
                - develop
                - release
      - apply_manifest:
          requires:
            - push_images
          filters:
            branches:
              only:
                - develop
      - aws-ecs/deploy-service-update:
          requires:
            - push_images
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=db_latest,tag=db_latest'
          filters:
            branches:
              only: 
                - develop
                - release
      - aws-ecs/deploy-service-update:
          requires:
            - push_images
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=db-migrate_latest,tag=db-migrate_latest'
          filters:
            branches:
              only: 
                - develop
                - release
      - aws-ecs/deploy-service-update:
          requires:
            - push_images
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=server_latest,tag=server_latest'
          filters:
            branches:
              only: 
                - develop
                - release
      - aws-ecs/deploy-service-update:
          requires:
            - push_images
          aws-region: ${AWS_REGION}
          family: '${MY_APP_PREFIX}'
          cluster-name: '${MY_APP_PREFIX}'
          service-name: '${MY_APP_PREFIX}'
          container-image-name-updates: 'container=client_latest,tag=client_latest'
          filters:
            branches:
              only: 
                - develop
                - release       
