name: Static Analysis

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'

jobs:
  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install bundle
        run:
          gem install bundler:2.0.1
          bundle install
        working-directory: ./backend
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh
          echo ::add-path::$HOME/bin
      - name: Run rubocop with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec rubocop | reviewdog -reporter=github-pr-review -f=rubocop -diff="git diff develop"